# Generated by Django 5.1.6 on 2025-03-05 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ward_number",
                    models.CharField(
                        help_text="Ward assigned to the official", max_length=10
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department of the official",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        help_text="Official's contact number",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officialprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
