# Generated by Django 5.1.6 on 2025-03-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorities", "0003_alter_complaintupdate_complaint_and_more"),
        ("complaints", "0005_delete_complaintupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintupdate",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="complaints.complaint",
            ),
        ),
        migrations.AlterField(
            model_name="complaintupdate",
            name="official",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authorities.governmentofficial",
            ),
        ),
    ]
