# Generated by Django 5.1.6 on 2025-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="ward_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
