# Generated by Django 5.1.6 on 2025-03-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorities", "0003_alter_complaintupdate_complaint_and_more"),
        ("complaints", "0002_complaint_latitude_complaint_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("update_description", models.TextField(blank=True, null=True)),
                ("proof_image", models.ImageField(upload_to="complaint_updates/")),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint_updates",
                        to="complaints.complaint",
                    ),
                ),
                (
                    "official",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_complaint_updates",
                        to="authorities.governmentofficial",
                    ),
                ),
            ],
        ),
    ]
