# Generated by Django 5.1.6 on 2025-03-05 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_complaintupdate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaintupdate",
            name="status",
        ),
        migrations.AlterField(
            model_name="complaintupdate",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="complaints.complaint",
            ),
        ),
        migrations.AlterField(
            model_name="complaintupdate",
            name="official",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="complaintupdate",
            name="proof_image",
            field=models.ImageField(blank=True, null=True, upload_to="updates/"),
        ),
        migrations.AlterField(
            model_name="complaintupdate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
