# Generated by Django 5.1.6 on 2025-03-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_remove_complaintupdate_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComplaintUpdate",
        ),
    ]
