# Generated by Django 5.1.6 on 2025-03-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0006_complaint_is_trashed_complaint_trashed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="is_permanently_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="permanently_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
